server:
  port: 9090
spring:
  application:
    name: amazing-online-class
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/amazing_user?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 12345678
  redis:
    host: 47.92.171.110
    port: 8000
    password: 123456
  mail:
    host: smtp.189.cn
    password: Lf=3Qm!7x)9Jo*3E
    username: 18911717812@189.cn
    from: 18911717812@189.cn
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: UTF-8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    root: INFO