#server:
#  port: 9089
#spring:
#  application:
#    name: amazing-gateway-service
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 47.92.171.110:8848
#    gateway:
#      routes:
#        - id: product-service
#          uri: lb://amazing-product-service
#          order: 1
#          predicates:
#            - Path=/product-server/**
#          filters:
#            - StripPrefix=1
#
#        - id: user-service
#          uri: lb://amazing-user-service
#          order: 1
#          predicates:
#            - Path=/user-server/**
#          filters:
#            - StripPrefix=1
#
#        - id: order-service
#          uri: lb://amazing-order-service
#          order: 1
#          predicates:
#            - Path=/order-server/**
#          filters:
#            - StripPrefix=1
#
#        - id: coupon-service
#          uri: lb://amazing-coupon-service
#          order: 1
#          predicates:
#            - Path=/coupon-server/**
#          filters:
#            - StripPrefix=1
#
#      discovery:
#        locator:
#          enabled: true
#
#logging:
#  level:
#    root: INFO
#    com.alibaba.nacos.client.config.impl: WARN
