server:
  port: 9094
spring:
  application:
    name: amazing-order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/amazing_order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 12345678
  redis:
    host: 47.92.171.110
    port: 8000
    password: 123456
  mail:
    host: smtp.189.cn
    password: Lf=3Qm!7x)9Jo*3E
    username: 18911717812@189.cn
    from: 18911717812@189.cn
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: UTF-8
  cloud:
    nacos:
      discovery:
        server-addr: 47.92.171.110:8848
  rabbitmq:
    host: 47.92.171.110
    port: 5672
    virtual-host: /
    password: 123456
    username: admin
    listener:
      simple:
        acknowledge-mode: manual
aliyun:
  oss:
    endpoint: oss-cn-zhangjiakou.aliyuncs.com
    access-key-id: LTAI5tMZyJFkTDVMi67yiGJB
    access-key-sercret: KiXVB9SkKGL2dMp4sMTGL2cCzRY3FB_b@$B
    bucketname: onlineclass-bucket

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    root: INFO

mqconfig:
  order_close_delay_queue: order.close.delay_queue
  order_close_queue: order.close.queue
  order_event_exchange: order.event.exchange
  order_close_delay_routing_key: order.close.delay.routing.key
  order_close_routing_key: order.close.routing.key
  ttl: 15000