server:
  port: 9093
spring:
  application:
    name: amazing-coupon-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/amazing_coupon?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 12345678
  redis:
    host: 47.92.171.110
    port: 8000
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 47.92.171.110:8848
  rabbitmq:
    host: 47.92.171.110
    port: 5672
    virtual-host: /
    password: 123456
    username: admin
    listener:
      simple:
        acknowledge-mode: manual


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    root: INFO

#seata:
#  tx-service-group: ${spring.application.name}-group
#  service:
#    grouplist:
#      amazing: 127.0.0.1:8091
#    vgroup-mapping:
#      amazing-coupon-service-group: amazing

mqconfig:
  coupon_release_delay_queue: coupon.release.delay_queue
  coupon_release_queue: coupon.release.queue
  coupon_event_exchange: coupon.event.exchange
  coupon_release_delay_routing_key: coupon.release.delay.routing.key
  coupon_release_routing_key: coupon.release.routing.key
  ttl: 360000